# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Publish Library

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - run: bun add -d @angular/cli
      - run: bun install
      - run: bun ng test
      - run: bun ng build --configuration production ngx-translate-toolkit
        env:
          CI: true # to avoid interactive prompts during build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: dist/ngx-translate-toolkit

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/
      - run: ls -aR
      - run: npm publish
        # working-directory: dist/ngx-translate-toolkit
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
